[package]
name = "gap-buffer"
version = "0.1.0"
authors = ["Samuel Wilson <samWson@users.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
